[package]
name = "tejuino"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "magic"
harness = false

[[bench]]
name = "pregen"
harness = false
